[package]
name = "rubigo-yes"
version = "0.2.0"
authors = ["Patrick Elsen <pelsen@xfbs.net>"]

[dependencies]

[dependencies.clap]
version = "2.25.1"
default-features = false
features = []

[dev-dependencies]
regex = "0.2"
